### ISSUE TITLE
Autoroutes grises dans le profil vélo

### ISSUE THREAD

**Issue by jej** [OsmAnd-Rendering/Cycling#3]
Hey,
Je trouve dommage que le rendu des autoroutes soit minimisé avec une couleur grise, sous prétexte sans doute qu'on ne prend pas l'autoroute en vélo. Perso j'utilise le profil osmand parce que justement les autoroutes sont en rouge comme sur les "bonnes vieilles" cartes...
Les autoroutes peu visibles sur une carte, ça augmente le risque de bivouaquer pas loin, de s'en approcher trop près le soir et d'avoir à s'en éloigner au pire moment, de minimiser une zone qui peut être plus dense, plus pénible à passer, etc. Je préfère savoir qu'une autoroute est là, même quand elle n'est pas pour moi.
Voilà, juste mon avis. Merci,
J.

**Comment by Louis-LJ** [comment]
Salut,

tu peux choisir le style de routes dans OsmAnd dans le réglage de la carte en cliquant sur "Style des routes". ; )
