### ISSUE TITLE
Cycle node network route lines not rendered

### ISSUE THREAD

**Issue by matthijskooijman** [OsmAnd-Rendering/Cycling#4]
It seems that normal cycle routes are rendered, but for cycle node networks the nodes and the refs/labels of the routes are rendered, but not the actual route line. For example, see the below screenshot of [this area](https://www.openstreetmap.org/#map=14/50.5790/6.1697&layers=C), which shows the 3LR route, but omits the 52-53 node route line.

![image](https://github.com/OsmAnd-Rendering/Cycling/assets/194491/bb0aa49d-b8ba-4ff7-8414-118c6263173d)

If this is intentional, then consider this a feature request to allow enabling cycle node network routes as well (probably in a different color than the normal networks?).

**Comment by bobeeeze** [comment]
You're right, it's an error. We'll try to correct it soon.

**Comment by matthijskooijman** [comment]
I saw in the Rendering Dev matrix/telegram channel that you have been looking into this issue (but not sure if my messages have reached you, not sure if the bridging works without a telegram account on my side).

I've also been looking at this issue (but also trying to understand the rendering files in general, this was a nice testcase) and it seems that the `routes.addon.render.xml` file from OsmAnd renders the route lines properly when I remove all route-related XML from the CycloRoute style, so apparently the CycloRoute makes a change to the routing lines that either prevents some styling from the routes addon from being used at all, or otherwise produces an invisible rendering (on the channel you talked about transparency, I think). Anyway, this is probably all already clear to you, I'm just learning this :-)

**Comment by bobeeeze** [comment]
I've just updated the rendering and fixed what was preventing node cycling networks from being displayed. They're displayed correctly now, as you can see in my screenshot
![photo_2024-05-10_18-48-03](https://github.com/OsmAnd-Rendering/Cycling/assets/59626956/7a928eca-f49a-467a-9b9e-ecff0ffb5c31)

**Comment by matthijskooijman** [comment]
Works perfectly for me too, thanks!
