### ISSUE TITLE
Road surface colors not in legend

### ISSUE THREAD

**Issue by matthijskooijman** [OsmAnd-Rendering/Cycling#5]
With this style, you can enable road surface marking in the settings, but these are not included in the legend.

**Comment by matthijskooijman** [comment]
I was referring to the legend at https://www.cyclosm.org/legend.html, but I just realized that this is the generic CyclOSM legend, not specific to this rendering style, so maybe it is not feasible to include it in *that* legend. I suspect that the surface colors are the same as in the OsmAnd style, so maybe a reference to a legend for that (if it exists) might suffice.

**Comment by bobeeeze** [comment]
We have included a link to the CyclOSM legend because we wanted to create a rendering style as close as possible to the one of CyclOSM. Maybe in the future we'll try to put a real legend.
