### ISSUE TITLE
Indentation of render XML is inconsistent

### ISSUE THREAD

**Issue by matthijskooijman** [OsmAnd-Rendering/Cycling#6]
Most of the file is indented with hard tabs, but some lines use spaces or are mixed. From those lines, I think the intention is that a hard tab is displayed as two spaces, but some lines (e.g. renderingProperty/Attribute/Constant lines at the start) actually seem to use a single space as indentation.

I think the file should either use hard tabs everywhere (to allow everyone to view the file in their favorite indent size, but this sometimes requires mixing with space for e.g. column alignment in comments or so), or use spaces everywhere (so it just looks the same and is less confusing). I normally prefer spaces, but that does produce a bigger diff (it seems about 250 of the 1900 lines currently use spaces).

Maybe it would be worthfile to use some xml linter/formatter for this? I could have a look at this and maybe pepare a PR if you're interested.

**Comment by Louis-LJ** [comment]
Good idea! 
Have you already made the changes?

**Comment by bobeeeze** [comment]
I've just updated the rendering and taken the opportunity to correct the indentation. I've replaced all the spaces with tabs.
@matthijskooijman  let me know if it looks OK

**Comment by matthijskooijman** [comment]
Looks good to me! Thanks, closing this issue!
