### ISSUE TITLE
Day/Night mode setting ignored

### ISSUE THREAD

**Issue by langfingaz** [OsmAnd-Rendering/Cycling#7]
Hi there :wave: Many thanks for this great map style for cycling!

Tonight, I imported this style into OsmAnd. When I switched to the "CycloRoute" profile, it was in the "Dark" mode:

<img src='https://github.com/OsmAnd-Rendering/Cycling/assets/10504672/18aab2c0-6831-462c-ab52-cc3a52248c22' width='250'>

While it is good to have a dark mode, I prefer to use the light version. So I went into the settings of the "CycloRoute" profile. In the submenu "General settings" I changed the **"App theme"** to **"Light"**:

<img src='https://github.com/OsmAnd-Rendering/Cycling/assets/10504672/a28df64a-0a7d-4ac8-bc7b-9b50571e6b0f' width='250'>

Nevertheless, the style did not change. It was **still in dark mode**.

After I manually set the time of my smartphone to 12:00 and restarted the app, I got the light mode.

Could this be a bug in OsmAnd itself or does this behavior come from this theme? All other themes stay in the light mode at night as I have configured their "App theme" to "Light". Only this custom theme seems to ignore the setting.

Any ideas what I could try to fix it? Maybe I could change the variable "daynight_mode" in here: https://github.com/OsmAnd-Rendering/Cycling/blob/0865ee46d3d1c261a9de22dc78e4efee5319a681/build.osf/profile_bicycle.json#L49

Greetings, Daniel

**Comment by bobeeeze** [comment]
Hi,
In the general settings of CycloRoute profile you only change the appearance of the menu. If you want to change the appearance of the map, you have to go to "configure map" and go to "map mode". Here you can choose between Sunrise/sunset, day, night and Light sensor. Day mode works fine, night mode works fine, light sensor mode works fine and I haven't tried the sunrise/ sunset mode but it must also work

**Comment by langfingaz** [comment]
Oh, you are totally right. Changing your mentioned setting to day works as expected. Sorry for the inconvenience, I'll close this as there is no bug.
