### ISSUE TITLE
Cycle paths disappear when zooming out

### ISSUE THREAD

**Issue by matei-oltean** [OsmAnd-Rendering/Cycling#9]
Hi,
When zooming out a little bit (which is useful when planning a trip), the cycle paths are not rendered any more, see pictures below:
<img src="https://github.com/OsmAnd-Rendering/Cycling/assets/17927847/5f85f8fa-4ab8-4210-b656-a9f98188e933" width="200" />
and when zooming out
<img src="https://github.com/OsmAnd-Rendering/Cycling/assets/17927847/52326177-a634-4092-ad04-d4cea9def6e9" width="200" />

(and thanks a lot for the work you are doing for the community!)

**Comment by aryvini** [comment]
Im having the same issue.

**Comment by bobeeeze** [comment]
Cycle routes only appear from zoom 11 but not because of a rendering style problem, but because the osmand devs have decided that they don't have to appear and don't take into account cycle routes in zoom layers up to 10 when creating the maps.

**Comment by bobeeeze** [comment]
You can see this closed issue in Osmand Github 
https://github.com/osmandapp/OsmAnd/issues/15213
